// Meta Menu
let mMetaMenu = [
  {
    nameMenu: "menu1",
    classFather: ".menu",
    mArray: "mMenu1",
    position: "relative",
    top: "",
    left: "",
    color: "Black",
    backgroundColor: 'darkgreen',
    margin: "0",
    padding: "0",
    border: "",
    borderRadius: "",
    fontSize: "1"
  },
  {
    nameMenu: "submenu12",
    classFather: "li[class='Item12']",
    mArray: "mMenu12",
    position: "relative",
    top: "100%",
    left: "0%",
    color: "brown",
    backgroundColor: 'white',
    margin: "0px 5px 5px 5px",
    padding: "0",
    border: "3px solid black",
    borderRadius: "3%",
    fontSize: "1"
  },
  {
    nameMenu: "submenu13",
    classFather: "li[class='Item13']",
    mArray: "mMenu13",
    position: "relative",
    top: "100%",
    left: "0%",
    color: "White",
    backgroundColor: 'darkcyan',
    margin: "0",
    padding: "0",
    border: "3px solid black",
    borderRadius: "3%",
    fontSize: "1"
  },
  {
    nameMenu: "trimenu121",
    classFather: "li[class='subItem121']",
    mArray: "mMenu121",
    position: "relative",
    top: "",
    left: "",
    color: "Black",
    backgroundColor: 'tomato',
    margin: "0",
    padding: "0",
    border: "",
    borderRadius: "",
    fontSize: "75%"
  },
  {
    nameMenu: "trimenu122",
    classFather: "li[class='subItem122']",
    mArray: "mMenu122",
    position: "relative",
    top: "",
    left: "",
    color: "Black",
    backgroundColor: 'darkslategray',
    margin: "0",
    padding: "0",
    border: "",
    borderRadius: "",
    fontSize: "75%"
  },
  {
    nameMenu: "trimenu133",
    classFather: "li[class='subItem133']",
    mArray: "mMenu133",
    position: "relative",
    top: "",
    left: "",
    color: "Black",
    backgroundColor: 'chocolate',
    margin: "0",
    padding: "0",
    border: "",
    borderRadius: "",
    fontSize: "75%"
  }
];

// Menus
let mMenu1 = [
  {
    nameItem: "Item11",
    option: 'Home',
    msg: 'Como en casa...',
    action: 'act_Home',
    top: "",
    left: "",
    color: 'black',
    backgroundColor: 'violet',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 0
  },
  {
    nameItem: "Item12",
    option: 'About',
    msg: 'A cerca de...',
    action:  '', //act_About',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 1
  },
  {
    nameItem: "Item13",
    option: 'Products',
    msg: 'Nuestros productos...',
    action: '', //'act_Products',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 2
  },
  {
    nameItem: "Item14",
    option: 'Contact',
    msg: 'Contactanos en...',
    action: 'act_Contact',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 3
  },
  {
    nameItem: "Item15",
    option: 'Clients',
    msg: 'Nuestros clientes...',
    action: 'act_Clients',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "3px solid gray",
    borderRadius: "10%",
    fontSize: "",
    id: 4
  }
];

let mMenu12 = [
  {
    nameItem: "subItem121",
    option: 'Opt121',
    msg: 'Opt12...',
    action: '', //'act12_Opt1',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 0
  },
  {
    nameItem: "subItem122",
    option: 'Opt122',
    msg: 'Opt122...',
    action: '', //'act12_Opt2',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 1
  }
];

let mMenu13 = [
  {
    nameItem: "subItem131",
    option: 'Opt131',
    msg: 'Opt131...',
    action: 'act13_Opt1',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 0
  },
  {
    nameItem: "subItem132",
    option: 'Opt132',
    msg: 'Opt132...',
    action: 'act13_Opt2',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 1
  },
  {
    nameItem: "subItem133",
    option: 'Opt133',
    msg: 'Opt133...',
    action: '', //'act13_Opt3',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 2
  },
  {
    nameItem: "subItem134",
    option: 'Opt134',
    msg: 'Opt134...',
    action: 'act13_Opt4',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 3
  },
  {
    nameItem: "subItem135",
    option: 'Opt135',
    msg: 'Opt135...',
    action: 'act13_Opt5',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 4
  }
];

let mMenu121 = [
  {
    nameItem: "triItem1211",
    option: 'Opt1211',
    msg: 'Opt1211...',
    action: 'act121_Opt1',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 0
  },
  {
    nameItem: "triItem1212",
    option: 'Opt1212',
    msg: 'Opt1212...',
    action: 'act121_Opt2',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 1
  }
];

let mMenu122 = [
  {
    nameItem: "triItem1221",
    option: 'Opt1221',
    msg: 'Opt1221...',
    action: 'act122_Opt1',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 0
  },
  {
    nameItem: "triItem1222",
    option: 'Opt1222',
    msg: 'Opt1222...',
    action: 'act122_Opt2',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 1
  }
];

let mMenu133 = [
  {
    nameItem: "triItem1331",
    option: 'Opt1331',
    msg: 'Opt1331...',
    action: 'act133_Opt1',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 0
  },
  {
    nameItem: "triItem1332",
    option: 'Opt1332',
    msg: 'Opt1332...',
    action: 'act133_Opt2',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 1
  },
  {
    nameItem: "triItem1333",
    option: 'Opt1333',
    msg: 'Opt1333...',
    action: 'act133_Opt3',
    top: "",
    left: "",
    color: '',
    backgroundColor: '',
    padding: "1em",
    margin: "",
    border: "",
    borderRadius: "",
    fontSize: "",
    id: 1
  }
];
